name: Unity License Activation

on:
  workflow_dispatch:

jobs:
  activate_license:
    runs-on: windows-latest

    steps:
      - name: Install Unity 2021.3.1f1
        run: |
          curl -o UnitySetup.exe https://download.unity3d.com/download_unity/2021.3.1f1/Windows64EditorInstaller/UnitySetup64.exe
          Start-Process -Wait -NoNewWindow -FilePath UnitySetup.exe -ArgumentList "/S /D=C:\Unity"
        shell: pwsh
  
      - name: Generate Unity Activation Request
        run: |
          "C:\Program Files\Unity\Hub\Editor\2021.3.1f1\Editor\Unity.exe" -batchmode -quit -createManualActivationFile
        shell: cmd

      - name: Upload Activation File
        uses: actions/upload-artifact@v4
        with:
          name: UnityLicenseRequest
          path: Unity_v2021.x.alf
