name: Build OpenRCT2-Unity UWP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set Up Developer Command Prompt
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"

      - name: Build OpenRCT2 Core
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          msbuild openrct2.proj /t:build /p:Platform=x64 /p:configuration=release

      - name: Build openrct2-bindings
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          msbuild src/openrct2-bindings/openrct2-bindings.vcxproj /p:Configuration=Release /p:Platform=x64
    
      - name: Build OpenRCT2-Unity for UWP
        id: build
        uses: buildalon/unity-uwp-builder@v1.0.4
        with:
          projectPath: 'src/openrct2-unity'
          buildTarget: 'UWP'
          outputPath: 'BuildOutput'

      - name: Upload UWP Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenRCT2-UWP
          path: ${{ steps.build.outputs.executable }}
