name: Build OpenRCT2-Unity (UWP)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Visual Studio 2022 Build Tools
      shell: powershell
      run: |
        $Dest = "C:\\tmp\\vs_buildtools.exe"
        Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile $Dest
        $Params = @(
          "--add Microsoft.VisualStudio.Workload.UniversalBuildTools", # Universal Windows Platform Development
          "--add Microsoft.VisualStudio.Component.Windows10SDK.19041", # Win10 SDK 19041
          "--quiet",
          "--wait"
        )
        Start-Process -FilePath $Dest -ArgumentList ($Params -join " ") -Wait
        Remove-Item $Dest
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Unity Project for UWP
      run: |
        Unity.exe -batchmode -quit -nographics -logFile unity.log -projectPath . -executeMethod UnityEditor.BuildPipeline.BuildPlayer -buildTarget WSAPlayer -customBuildPath Build/UWP -customBuildTarget WSAPlayer -customBuildName OpenRCT2-Unity-UWP

    - name: Build UWP Solution
      run: |
        msbuild Build/UWP/OpenRCT2-Unity.sln /p:Configuration=Release /p:Platform=x64 /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UWP-Build
        path: Build/UWP/AppPackages

    - name: Upload Unity Package
      uses: actions/upload-artifact@v4
      with:
        name: Unity-Package
        path: Build/OpenRCT2-Unity.unitypackage
